"""
batch_render_freesound.py
-------------------------
Renders all Mantice presets and generates a Freesound bulk-upload CSV.

Usage:
    python batch_render_freesound.py

Output:
    exports/freesound/       — WAV files (24-bit/48kHz, 120s each)
    exports/freesound.csv    — Freesound bulk descriptor CSV
"""

import csv
import random
import sys
from pathlib import Path

import numpy as np

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent))

from engine import config
from engine.config import set_hires
from engine.preset_loader import load_preset
from engine.drone_engine import DroneEngine
from engine.exporter import export_audio
# ── Configuration ─────────────────────────────────────────────────────────────

DURATION = 120          # seconds per render
SEED = 42              # reproducible renders
OUTPUT_DIR = Path("exports/freesound")
CSV_PATH = Path("exports/freesound.csv")
PRESETS_DIR = Path("presets")

# Freesound metadata defaults
FS_LICENSE = "Creative Commons 0"
FS_GEOTAG = ""
FS_PACK = "Mantice - Procedural Ambient Drones"

# Category → Freesound description prefix
CATEGORY_DESCRIPTIONS = {
    "essentials": "A warm, accessible ambient drone",
    "cinematic": "A cinematic ambient drone texture",
    "experimental": "An experimental procedural drone",
    "sacred": "A sacred/meditative ambient drone",
    "subharmonic": "A deep sub-bass drone texture",
}

def build_description(preset: dict, category: str, filename: str) -> str:
    """Build a Freesound description from preset metadata."""
    meta = preset.get("meta", {})
    name = meta.get("name", filename)
    desc_parts = [
        f"{CATEGORY_DESCRIPTIONS.get(category, 'A procedural ambient drone')} "
        f"generated by Mantice.",
        "",
        f"Preset: {name}",
        f"Category: {category}",
        f"Duration: {DURATION}s",
        f"Format: WAV 24-bit / 48kHz stereo",
        "",
        "Generated with Mantice — a procedural sacred/ambient drone generator",
        "using FM synthesis, granular clouds, spatial panning, binaural beats,",
        "and FDN reverb.",
        "",
        "https://github.com/bassimatte/mantice",
    ]
    
    # Add layer info
    layers = preset.get("layers", [])
    if layers:
        desc_parts.append("")
        desc_parts.append(f"Layers: {len(layers)}")
        for i, layer in enumerate(layers):
            root = layer.get("synthesis", {}).get("root", "?")
            desc_parts.append(f"  Layer {i+1}: {layer.get('name', f'Layer {i+1}')} ({root} Hz)")
    
    return "\n".join(desc_parts)


def build_tags(preset: dict, category: str) -> str:
    """Build Freesound tags from preset metadata."""
    base_tags = ["drone", "ambient", "procedural", "mantice", "synthesizer", "generative"]
    
    meta = preset.get("meta", {})
    preset_tags = meta.get("tags", [])
    
    # Add category as tag
    all_tags = base_tags + [category] + preset_tags
    
    # Add binaural tag if present
    binaural = preset.get("binaural") or {}
    if binaural.get("enabled", False):
        all_tags.append("binaural")
    
    # Add granular tag if any layer uses it
    for layer in preset.get("layers", []):
        if layer.get("granular", {}).get("enabled", False):
            all_tags.append("granular")
            break
    
    # Deduplicate and clean
    seen = set()
    clean_tags = []
    for t in all_tags:
        t_clean = t.lower().replace(" ", "-")
        if t_clean not in seen and len(t_clean) > 1:
            seen.add(t_clean)
            clean_tags.append(t_clean)
    
    return " ".join(clean_tags[:30])  # Freesound max ~30 tags


def main():
    # Switch to hi-res mode (48kHz/24-bit)
    set_hires()
    
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    # Discover all presets
    preset_files = sorted(PRESETS_DIR.rglob("*.yaml"))
    print(f"Found {len(preset_files)} presets to render.\n")
    print(f"Output: {OUTPUT_DIR.resolve()}")
    print(f"Format: WAV 24-bit / 48kHz / {DURATION}s\n")
    print("=" * 60)
    
    rows = []
    
    for i, preset_path in enumerate(preset_files, 1):
        rel = preset_path.relative_to(PRESETS_DIR)
        category = rel.parts[0] if len(rel.parts) > 1 else "uncategorized"
        name = preset_path.stem
        
        print(f"[{i:2}/{len(preset_files)}] {category}/{name}...", end=" ", flush=True)
        
        try:
            preset = load_preset(preset_path)
        except Exception as e:
            print(f"SKIP (load error: {e})")
            continue
        
        # Override duration
        preset["duration"] = DURATION
        
        # Render
        try:
            random.seed(SEED)
            np.random.seed(SEED)
            engine = DroneEngine(preset)
            audio = engine.build()
        except Exception as e:
            print(f"SKIP (render error: {e})")
            continue
        
        # Export WAV
        safe_name = name.replace(" ", "_").replace("/", "_")
        wav_filename = f"Mantice_{category}_{safe_name}.wav"
        wav_path = OUTPUT_DIR / wav_filename
        export_audio(wav_path, audio, fmt="wav")
        
        print(f"✓ ({audio.shape[0] / config.SAMPLE_RATE:.0f}s)")
        
        # Build CSV row
        rows.append({
            "audio_filename": wav_filename,
            "name": f"Mantice - {name}",
            "tags": build_tags(preset, category),
            "geotag": FS_GEOTAG,
            "description": build_description(preset, category, name),
            "license": FS_LICENSE,
            "pack": FS_PACK,
            "is_explicit": "0",
        })
    
    # Write CSV
    print("\n" + "=" * 60)
    print(f"Writing CSV: {CSV_PATH}")
    
    CSV_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(CSV_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "audio_filename", "name", "tags", "geotag",
            "description", "license", "pack", "is_explicit"
        ])
        writer.writeheader()
        writer.writerows(rows)
    
    print(f"\n✓ Done! Rendered {len(rows)} files.")
    print(f"  Audio: {OUTPUT_DIR.resolve()}")
    print(f"  CSV:   {CSV_PATH.resolve()}")
    print(f"\nUpload to: https://freesound.org/home/bulk_describe/")


if __name__ == "__main__":
    main()
