"""
batch_render_freesound.py
-------------------------
Renders all Mantice presets and generates a Freesound bulk-upload XLSX.

Usage:
    python batch_render_freesound.py              — render all + generate XLSX
    python batch_render_freesound.py --metadata-only  — regenerate XLSX only (skip rendering)

Output:
    exports/freesound/            — WAV files (24-bit/48kHz, 120s each)
    exports/freesound_bulk.xlsx   — Freesound bulk descriptor (matches their template)
"""

import random
import sys
from pathlib import Path

import numpy as np

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent))

from engine import config
from engine.config import set_hires
from engine.preset_loader import load_preset
from engine.drone_engine import DroneEngine
from engine.exporter import export_audio

# ── Configuration ─────────────────────────────────────────────────────────────

DURATION = 120          # seconds per render
SEED = 42              # reproducible renders
OUTPUT_DIR = Path("exports/freesound")
XLSX_PATH = Path("exports/freesound_bulk.xlsx")
PRESETS_DIR = Path("presets")

# Freesound metadata defaults
FS_LICENSE = "Creative Commons 0"
FS_PACK = "Ambient Drones by Mantice"
# BST category: "m-m" = Music > Music
FS_BST_CATEGORY = "m-m"

# Category → Freesound description prefix
CATEGORY_DESCRIPTIONS = {
    "essentials": "A warm, accessible ambient drone",
    "cinematic": "A cinematic ambient drone texture",
    "experimental": "An experimental procedural drone",
    "sacred": "A sacred/meditative ambient drone",
    "subharmonic": "A deep sub-bass drone texture",
    "generated": "A procedurally generated ambient drone",
}


MANTICE_INFO = (
    "Mantice is a procedural ambient drone generator. The name comes from the Italian "
    "word for organ bellows - the invisible breath engine that gives life to the pipes. "
    "Like a mantice, this tool provides the continuous, living airflow beneath your sound.\n\n"
    "Unlike sample-based instruments or DAW plugins, Mantice generates audio from mathematical "
    "processes - every sound is computed in real-time from oscillators, noise, and grain clouds. "
    "No two renders are ever exactly alike (unless you lock the seed).\n\n"
    "A Mantice preset consists of 1-5 independent layers, each with its own frequency, timbre, "
    "spatial position, and movement. Layers are mixed together to create complex, evolving "
    "textures - like individual instruments in an ensemble, each contributing a different voice "
    "to the whole.\n\n"
    "Each layer uses Frequency Modulation (FM) synthesis as its core. Multiple detuned voices "
    "per layer create rich, beating textures. The FM index controls harmonic complexity - low "
    "values produce pure tones, higher values create metallic, bell-like timbres. On top of FM, "
    "each layer adds harmonic overtones (up to 16 partials with configurable decay) and filtered "
    "noise (white, pink, or brown) for breath-like textures and organic warmth.\n\n"
    "Layers can also be granular - extracting tiny overlapping slices (grains) from real audio "
    "recordings. The included samples (singing bowls, gongs, bowed glass, throat singing, water, "
    "wind) become raw material for evolving textures impossible with pure synthesis.\n\n"
    "Each layer has a position in 3D space - horizontal (left/right, front/back) and vertical "
    "(elevation). Layers can move through space using trajectories: orbit, drift, bounce, or "
    "random. This creates an immersive, living soundfield - especially powerful with headphones.\n\n"
    "Global processing includes: soft saturation (analog tape-like warmth via tanh waveshaping), "
    "an 8-line Feedback Delay Network reverb with Hadamard mixing and per-line damping, optional "
    "binaural beat entrainment (Delta/Theta/Alpha/Beta brainwave bands), and Earth & Air layers "
    "that extend the frequency range with sub-bass tectonic rumble and high-frequency breath "
    "turbulence."
)


def build_description(preset: dict, category: str, filename: str) -> str:
    """Build a Freesound description from preset metadata."""
    prefix = CATEGORY_DESCRIPTIONS.get(category, "A procedural ambient drone")
    return (
        f"{prefix} generated by MANTICE (https://github.com/bassimatte/mantice).\n\n"
        f"{MANTICE_INFO}"
    )


def build_tags(preset: dict, category: str) -> str:
    """Build Freesound tags from preset metadata (space-separated)."""
    base_tags = ["drone", "ambient", "procedural", "mantice", "synthesizer",
                 "generative", "texture", "soundscape", "meditation", "relaxation",
                 "atmospheric", "electronic", "evolving", "immersive", "spatial",
                 "deep", "cinematic", "dark-ambient", "fm-synthesis", "pad"]
    
    # Category-specific extra tags
    category_tags = {
        "essentials": ["warm", "gentle", "minimal", "soft", "calm"],
        "cinematic": ["film", "tension", "score", "dramatic", "suspense", "movie"],
        "experimental": ["experimental", "abstract", "avant-garde", "glitch", "noise"],
        "sacred": ["sacred", "ritual", "spiritual", "healing", "ceremonial", "tibetan"],
        "subharmonic": ["sub-bass", "rumble", "low-frequency", "bass", "seismic"],
        "generated": ["algorithmic", "random", "machine-generated"],
    }
    
    meta = preset.get("meta", {})
    preset_tags = meta.get("tags", [])
    
    all_tags = base_tags + category_tags.get(category, []) + [category] + preset_tags
    
    # Add binaural tag if present
    binaural = preset.get("binaural") or {}
    if binaural.get("enabled", False):
        all_tags.extend(["binaural", "binaural-beats", "brainwave"])
    
    # Add granular tag if any layer uses it
    for layer in preset.get("layers", []):
        if layer.get("type") == "granular":
            all_tags.extend(["granular", "granular-synthesis", "grain"])
            break
    
    # Add reverb-related tags
    reverb = preset.get("reverb") or {}
    if reverb:
        space = reverb.get("space", "")
        if space:
            all_tags.append(space)  # cathedral, cave, hall, etc.
    
    # Deduplicate and clean
    seen = set()
    clean_tags = []
    for t in all_tags:
        t_clean = t.lower().replace(" ", "-")
        if t_clean not in seen and len(t_clean) > 1:
            seen.add(t_clean)
            clean_tags.append(t_clean)
    
    return " ".join(clean_tags[:30])


def main():
    from openpyxl import Workbook

    metadata_only = "--metadata-only" in sys.argv

    # Switch to hi-res mode (48kHz/24-bit)
    set_hires()
    
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    # Discover all presets
    preset_files = sorted(PRESETS_DIR.rglob("*.yaml"))
    print(f"Found {len(preset_files)} presets.\n")
    if not metadata_only:
        print(f"Output: {OUTPUT_DIR.resolve()}")
        print(f"Format: WAV 24-bit / 48kHz / {DURATION}s\n")
    else:
        print("Mode: --metadata-only (skip rendering, generate XLSX only)\n")
    print("=" * 60)
    
    rows = []
    
    for i, preset_path in enumerate(preset_files, 1):
        rel = preset_path.relative_to(PRESETS_DIR)
        category = rel.parts[0] if len(rel.parts) > 1 else "uncategorized"
        name = preset_path.stem
        
        print(f"[{i:2}/{len(preset_files)}] {category}/{name}...", end=" ", flush=True)
        
        try:
            preset = load_preset(preset_path)
        except Exception as e:
            print(f"SKIP (load error: {e})")
            continue
        
        # Override duration
        preset["duration"] = DURATION
        
        safe_name = name.replace(" ", "_").replace("/", "_")
        wav_filename = f"Mantice_{category}_{safe_name}.wav"

        if not metadata_only:
            # Render
            try:
                random.seed(SEED)
                np.random.seed(SEED)
                engine = DroneEngine(preset)
                audio = engine.build()
            except Exception as e:
                print(f"SKIP (render error: {e})")
                continue
            
            # Export WAV
            wav_path = OUTPUT_DIR / wav_filename
            export_audio(wav_path, audio, fmt="wav")
            print(f"✓ ({audio.shape[0] / config.SAMPLE_RATE:.0f}s)")
        else:
            print("✓")
        
        # Build row matching Freesound bulk template
        rows.append({
            "audio_filename": wav_filename,
            "name": f"{name} - {category.capitalize()} Drone by Mantice",
            "tags": build_tags(preset, category),
            "geotag": "",
            "description": build_description(preset, category, name),
            "license": FS_LICENSE,
            "pack_name": FS_PACK,
            "is_explicit": "0",
            "bst_category": FS_BST_CATEGORY,
        })
    
    # Write XLSX (Freesound bulk describe format)
    print("\n" + "=" * 60)
    print(f"Writing XLSX: {XLSX_PATH}")
    
    XLSX_PATH.parent.mkdir(parents=True, exist_ok=True)
    
    wb = Workbook()
    ws = wb.active
    ws.title = "Freesound Bulk Describe"
    
    # Header row (must match Freesound template exactly)
    headers = ["audio_filename", "name", "tags", "geotag",
               "description", "license", "pack_name", "is_explicit", "bst_category"]
    ws.append(headers)
    
    for row in rows:
        ws.append([row[h] for h in headers])
    
    wb.save(XLSX_PATH)
    
    print(f"\n✓ Done! Rendered {len(rows)} files.")
    print(f"  Audio: {OUTPUT_DIR.resolve()}")
    print(f"  XLSX:  {XLSX_PATH.resolve()}")
    print(f"\nUpload audio files, then use XLSX at: https://freesound.org/home/describe/")


if __name__ == "__main__":
    main()
