"""
main.py — MANTICE V26.0
---------------------
Usage:
    python main.py                              # process all presets
    python main.py --list                       # list available presets
    python main.py --preset path/to.yaml        # single preset by path
    python main.py --name "Breathing Cathedral" # run preset by name
    python main.py --duration 90                # override duration (seconds)
    python main.py --hires                      # render at 48kHz/24-bit
    python main.py --format flac               # export as FLAC (wav, flac, ogg, mp3)
    python main.py --seed 42                    # global reproducibility seed
    python main.py --auto-template journey      # apply automation template (journey/arc/breathe/meditate/sunrise/wander/trance/shimmer)
    python main.py --journey-template drift     # render journey quick-set (drift/flow/pulse/ceremony/dawn/shimmer)
    python main.py --no-automation              # strip all automation (static render)
    python main.py --preview --name "Cavern"   # real-time preview to speakers
    python main.py --preview --infinite        # infinite drone, Ctrl+C to stop
    python main.py --generate                  # generate a random preset
    python main.py --generate --mood dark      # generate with mood bias
    python main.py --gui                       # launch web UI in browser
    python main.py --mutate "Breathing Cathedral" --amount 0.3  # mutate existing
"""

import argparse
import csv
import random
import sys
import time
import warnings
from pathlib import Path
from typing import List, Optional

try:
    import openpyxl
    HAS_OPENPYXL = True
except ImportError:
    HAS_OPENPYXL = False

# ── Hi-res mode must be set before engine imports ────────────────────────────
if "--hires" in sys.argv:
    from engine.config import set_hires
    set_hires()

import numpy as np

from engine.preset_loader    import load_preset
from engine.streaming_engine import StreamingDroneEngine
from engine.exporter         import export_audio, SUPPORTED_FORMATS
from engine.generator        import generate_preset, mutate_preset, save_generated_preset, get_available_moods
from engine.automation       import apply_auto_template, strip_automation, TEMPLATE_NAMES
from engine                  import config as _engine_config

PRESET_DIR = Path("presets")
SHARED_DIR = Path("shared")
EXPORT_DIR = Path("exports")

EXPORT_DIR.mkdir(exist_ok=True)

CSV_COLUMNS = [
    "audio_filename", "name", "tags", "geotag",
    "description", "license", "pack_name", "is_explicit", "bst_category",
]


# ── helpers ───────────────────────────────────────────────────────────────────

def discover_presets() -> List[Path]:
    """Discover all presets from both official (presets/) and community (shared/) folders."""
    presets = []
    
    # Official presets
    if PRESET_DIR.exists():
        presets.extend(PRESET_DIR.rglob("*.yaml"))
    
    # Community presets
    if SHARED_DIR.exists():
        presets.extend(SHARED_DIR.glob("*.yaml"))  # Non-recursive for shared/
    
    return sorted(presets)


def apply_seed(preset: dict, cli_seed: Optional[int]) -> None:
    seed = cli_seed if cli_seed is not None else preset.get("seed")
    if seed is not None:
        random.seed(seed)
        np.random.seed(seed)


def build_tags(preset: dict) -> str:
    meta     = preset.get("meta", {})
    mood     = meta.get("mood") or []
    base     = ["drone", "ambient", "spatial", "sacred"]
    category = meta.get("category", "")
    if category and category not in base:
        base.append(category)
    all_tags = base + [m for m in mood if m not in base]
    return ", ".join(all_tags)


def build_freesound_description(preset: dict) -> str:
    """Build a detailed Freesound description in the style of the MANTICE uploads."""
    meta = preset.get("meta", {})
    preset_name = meta.get("name", "Untitled")
    
    description = f"A deep sub-bass drone texture generated by MANTICE.\n\n"
    description += "Web: https://bassimatte.github.io/mantice/\n"
    description += "GitHub: https://github.com/bassimatte/mantice\n\n"
    description += "Mantice is a procedural ambient drone generator. The name comes from the Italian word for organ bellows - the invisible breath engine that gives life to the pipes. Like a mantice, this tool provides the continuous, living airflow beneath your sound.\n\n"
    
    # Add preset-specific details if available
    if meta.get("description"):
        description += f"About this preset:\n{meta['description']}\n\n"
    
    description += "Unlike sample-based instruments or DAW plugins, Mantice generates audio from mathematical processes - every sound is computed in real-time from oscillators, noise, and grain clouds. No two renders are ever exactly alike (unless you lock the seed).\n\n"
    description += "A Mantice preset consists of 1-5 independent layers, each with its own frequency, timbre, spatial position, and movement. Layers are mixed together to create complex, evolving textures - like individual instruments in an ensemble, each contributing a different voice to the whole.\n\n"
    description += "Each FM layer uses Frequency Modulation synthesis as its core. Multiple detuned voices per layer create rich, beating textures. The FM index controls harmonic complexity - low values produce pure tones, higher values create metallic, bell-like timbres. On top of FM, each layer adds harmonic overtones (up to 16 partials with configurable decay) and filtered noise (white, pink, or brown) for breath-like textures and organic warmth.\n\n"
    description += "Subtractive layers use classic waveform oscillators (sawtooth, square, or triangle) instead of FM. Two detuned oscillator pairs create the thick, beating quality of a Reese bass. A third sub-oscillator one octave below adds weight. The output is shaped by the per-layer filter.\n\n"
    description += "Every layer has five filter modes: LP (low-pass), HP (high-pass), BP (band-pass), Comb, and Formant. LP/HP/BP are biquad filters with resonance and optional LFO modulation (sine/triangle/square) on the cutoff. Comb creates metallic ringing via feedforward delay. Formant shapes the sound into vowel resonances (A, E, I, O, U) using three parallel bandpass filters at human vocal formant frequencies.\n\n"
    description += "Layers can also be granular - extracting tiny overlapping slices (grains) from real audio recordings. The included samples (singing bowls, gongs, bowed glass, throat singing, water, wind) become raw material for evolving textures impossible with pure synthesis.\n\n"
    description += "Each layer has a position in 3D space - horizontal (left/right, front/back) and vertical (elevation). Layers can move through space using trajectories: orbit, drift, bounce, or random. This creates an immersive, living soundfield - especially powerful with headphones.\n\n"
    description += "Per-layer effects include: Chorus (modulated delay copies for width and shimmer), Flanger (short delay comb filter with LFO for jet-plane sweeps), Phaser (cascaded all-pass filter stages for notch sweeps), and Distortion.\n\n"
    description += "Global processing includes: 4x-oversampled soft saturation (analog tape-like warmth via tanh waveshaping), an 8-line Feedback Delay Network reverb with Hadamard mixing and per-line damping (or IR convolution mode with real impulse responses), Shimmer FX (pitch-shifted feedback tail for ethereal upward bloom), optional binaural beat entrainment (Delta/Theta/Alpha/Beta brainwave bands), Earth & Air layers (sub-bass tectonic rumble + high-frequency breath turbulence), Master EQ, Master Compressor, and Limiter.\n\n"
    description += "Parameter Automation allows any global or per-layer parameter to evolve over the duration using a breakpoint editor with linear, exponential, and S-curve interpolation. Five global automation templates (Journey, Arc, Breathe, Meditate, Sunrise) provide quick starting points.\n\n"
    description += "Just Intonation (JI) mode derives all layer frequencies from a single tonic via pure rational-fraction intervals (e.g. 3/2 for a perfect fifth, 5/4 for a major third), eliminating beating between layers - the defining quality of sustained sacred drone music."
    
    return description


def write_freesound_xlsx(xlsx_path: Path, audio_filename: str, preset: dict) -> None:
    """Generate Freesound bulk upload XLS file with proper metadata."""
    if not HAS_OPENPYXL:
        print("  ⚠️  openpyxl not installed, skipping XLS generation. Install with: pip install openpyxl", file=sys.stderr)
        return
    
    meta = preset.get("meta", {})
    
    # Create workbook
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Freesound Upload"
    
    # Headers (Freesound bulk upload format)
    headers = ["audio_filename", "name", "tags", "geotag", "description", "license", "pack_name", "is_explicit"]
    ws.append(headers)
    
    # Build metadata row
    row = [
        audio_filename,
        meta.get("name", Path(audio_filename).stem),
        build_tags(preset),
        "",  # geotag (empty)
        build_freesound_description(preset),
        "Creative Commons 0",
        "MANTICE Drones",
        "0"  # not explicit
    ]
    ws.append(row)
    
    # Auto-adjust column widths
    for col in ws.columns:
        max_length = 0
        col_letter = col[0].column_letter
        for cell in col:
            if cell.value:
                max_length = max(max_length, len(str(cell.value)))
        adjusted_width = min(max_length + 2, 100)  # Cap at 100 for description
        ws.column_dimensions[col_letter].width = adjusted_width
    
    # Save
    wb.save(xlsx_path)


def write_metadata_csv(csv_path: Path, audio_filename: str, preset: dict) -> None:
    """Legacy CSV metadata (kept for backward compatibility)."""
    meta = preset.get("meta", {})
    row  = {
        "audio_filename": audio_filename,
        "name":           meta.get("name", Path(audio_filename).stem),
        "tags":           build_tags(preset),
        "geotag":         "",
        "description":    meta.get("description", "Procedural sacred drone."),
        "license":        "Creative Commons 0",
        "pack_name":      "Drones",
        "is_explicit":    0,
        "bst_category":   "Drone",
    }
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_COLUMNS)
        writer.writeheader()
        writer.writerow(row)


# ── progress bar ──────────────────────────────────────────────────────────────

class ProgressBar:
    """Simple terminal progress bar (no external dependencies)."""

    def __init__(self, total: int, description: str = "", width: int = 40):
        self.total       = max(total, 1)
        self.description = description
        self.width       = width
        self.current     = 0
        self.start_time  = time.time()

    def update(self, n: int = 1) -> None:
        self.current = min(self.current + n, self.total)
        self._render()

    def _render(self) -> None:
        frac    = self.current / self.total
        filled  = int(self.width * frac)
        bar     = "█" * filled + "░" * (self.width - filled)
        percent = frac * 100
        elapsed = time.time() - self.start_time

        if self.current > 0 and frac < 1.0:
            eta = elapsed / frac * (1 - frac)
            time_str = f"ETA {eta:.0f}s"
        elif frac >= 1.0:
            time_str = f"{elapsed:.1f}s"
        else:
            time_str = "..."

        line = f"\r  {self.description} |{bar}| {percent:5.1f}% {time_str}"
        sys.stdout.write(line)
        sys.stdout.flush()

    def finish(self) -> None:
        self.current = self.total
        self._render()
        sys.stdout.write("\n")
        sys.stdout.flush()


# ── main ──────────────────────────────────────────────────────────────────────

def run(
    preset_paths: List[Path],
    cli_seed: Optional[int],
    cli_duration: Optional[float],
    audio_format: str,
    solo_layer: Optional[str] = None,
    auto_template: Optional[str] = None,
    no_automation: bool = False,
) -> None:
    ok = failed = 0
    total = len(preset_paths)

    for idx, preset_path in enumerate(preset_paths, 1):
        try:
            with warnings.catch_warnings(record=True) as caught:
                warnings.simplefilter("always")
                preset = load_preset(preset_path)
                for w in caught:
                    print(f"  ⚠  {w.message}")

            # Override duration from CLI if specified
            if cli_duration is not None:
                preset["duration"] = cli_duration

            # Apply / strip automation
            if no_automation:
                strip_automation(preset)
                print("  ⚙  Automation: disabled")
            elif auto_template:
                apply_auto_template(preset, auto_template)
                print(f"  ⚙  Automation template: {auto_template}")

            apply_seed(preset, cli_seed)

            name = preset["meta"].get("name", preset_path.stem)
            slug = preset["meta"].get("slug", preset_path.stem.lower().replace(" ", "_"))

            # ── Solo layer: disable all except the target ─────────────────
            solo_layer_name = None
            if solo_layer is not None:
                layers = preset["layers"]
                target_idx = None
                # Try as index first
                try:
                    idx_val = int(solo_layer)
                    if 0 <= idx_val < len(layers):
                        target_idx = idx_val
                except ValueError:
                    pass
                # Try as name match
                if target_idx is None:
                    query = solo_layer.lower()
                    for i, l in enumerate(layers):
                        if query in l.get("name", "").lower():
                            target_idx = i
                            break
                if target_idx is None:
                    print(f"  ✗ Layer '{solo_layer}' not found. Available layers:")
                    for i, l in enumerate(layers):
                        print(f"      {i}: {l.get('name', 'Layer ' + str(i))}")
                    failed += 1
                    continue
                # Disable all except target
                for i, l in enumerate(layers):
                    l["enabled"] = (i == target_idx)
                solo_layer_name = layers[target_idx].get("name", f"Layer {target_idx}")
                print(f"\n[{idx}/{total}] Generating: {name} — solo: {solo_layer_name}")
            else:
                print(f"\n[{idx}/{total}] Generating: {name}")

            # Build using StreamingDroneEngine (identical signal chain to web preview)
            seed = int(cli_seed) if cli_seed is not None else (preset.get("seed") or 42)
            engine = StreamingDroneEngine(preset, seed=seed)

            sr           = _engine_config.SAMPLE_RATE
            total_samp   = int(preset["duration"] * sr)
            chunk_size   = 2048
            n_chunks     = (total_samp + chunk_size - 1) // chunk_size
            progress     = ProgressBar(n_chunks, description="Rendering")
            chunks, rem  = [], total_samp
            while rem > 0:
                n = min(chunk_size, rem)
                chunks.append(engine.next_chunk(n))
                rem -= n
                progress.update(1)
            progress.finish()
            audio = np.concatenate(chunks, axis=0)

            # Export audio — append layer name if solo
            if solo_layer_name:
                safe_name = "".join(c for c in name if c.isalnum() or c in " -_").strip()
                safe_layer = "".join(c for c in solo_layer_name if c.isalnum() or c in " -_").strip()
                audio_filename = f"{safe_name} - Solo {safe_layer}.{audio_format}"
            else:
                audio_filename = f"{slug}.{audio_format}"
            out_path = EXPORT_DIR / audio_filename
            export_audio(out_path, audio, fmt=audio_format)
            print(f"  ✓ Saved: {out_path}")

            # Generate Freesound bulk upload XLS
            xlsx_path = EXPORT_DIR / f"{slug}.xlsx"
            write_freesound_xlsx(xlsx_path, audio_filename, preset)
            if HAS_OPENPYXL:
                print(f"  ✓ Freesound metadata: {xlsx_path}")

            ok += 1

        except Exception as exc:
            print(f"  ✗ Failed ({preset_path.name}): {exc}", file=sys.stderr)
            failed += 1

    print(f"\n{'─' * 40}")
    print(f"Done — {ok} exported, {failed} failed.")


def list_presets(preset_paths: List[Path]) -> None:
    """Print available presets in a readable table."""
    print(f"{'#':<4} {'Name':<30} {'Source':<12} {'Category':<14} {'Duration':<8} Path")
    print("─" * 110)
    for i, p in enumerate(preset_paths, 1):
        try:
            with warnings.catch_warnings(record=True):
                warnings.simplefilter("always")
                preset = load_preset(p)
            meta = preset.get("meta", {})
            name = meta.get("name", p.stem)
            cat  = meta.get("category", "—")
            dur  = f"{preset['duration']:.0f}s"
            # Check if community preset
            source = "Community" if p.parts[0] == "shared" else "Official"
            # Add author for community presets
            if source == "Community":
                author = meta.get("author", "")
                if author:
                    name = f"{name} (by {author})"
        except Exception:
            name, cat, dur = p.stem, "?", "?"
            source = "Community" if p.parts[0] == "shared" else "Official"
        print(f"{i:<4} {name:<30} {source:<12} {cat:<14} {dur:<8} {p}")
    
    # Summary
    official_count = sum(1 for p in preset_paths if p.parts[0] != "shared")
    community_count = sum(1 for p in preset_paths if p.parts[0] == "shared")
    print(f"\n{len(preset_paths)} preset(s) found: {official_count} official, {community_count} community.")


def find_preset_by_name(preset_paths: List[Path], name: str) -> List[Path]:
    """Find presets whose name or filename matches the query (case-insensitive)."""
    query = name.lower()
    matches = []
    for p in preset_paths:
        # Match against filename stem
        if query in p.stem.lower():
            matches.append(p)
            continue
        # Match against meta.name inside the file
        try:
            with warnings.catch_warnings(record=True):
                warnings.simplefilter("always")
                preset = load_preset(p)
            meta_name = preset.get("meta", {}).get("name", "")
            if query in meta_name.lower():
                matches.append(p)
        except Exception:
            pass
    return matches


def main() -> None:
    available_moods = get_available_moods()

    parser = argparse.ArgumentParser(description="Mantice V20.0")
    parser.add_argument(
        "--gui", action="store_true",
        help="Launch the web UI in your browser (requires fastapi & uvicorn)",
    )
    parser.add_argument(
        "--list", action="store_true",
        help="List all available presets and exit",
    )
    parser.add_argument(
        "--preview", action="store_true",
        help="Real-time preview: stream audio to speakers (requires sounddevice)",
    )
    parser.add_argument(
        "--infinite", action="store_true",
        help="Infinite mode: drone plays forever until Ctrl+C (use with --preview)",
    )
    parser.add_argument(
        "--generate", action="store_true",
        help="Generate a random preset and save to presets/generated/",
    )
    parser.add_argument(
        "--mood", type=str, default=None,
        choices=available_moods,
        help=f"Mood bias for --generate. Options: {', '.join(available_moods)}",
    )
    parser.add_argument(
        "--generate-count", type=int, default=1,
        help="Number of presets to generate (default: 1)",
    )
    parser.add_argument(
        "--mutate", type=str, default=None, metavar="PRESET_NAME",
        help="Mutate an existing preset (by name) and save variation to presets/generated/",
    )
    parser.add_argument(
        "--amount", type=float, default=0.3,
        help="Mutation amount (0.0 = identical, 1.0 = wild). Default: 0.3",
    )
    parser.add_argument(
        "--preset", type=Path, default=None,
        help="Path to a single preset file (.yaml)",
    )
    parser.add_argument(
        "--name", type=str, default=None,
        help="Run preset(s) matching this name (case-insensitive search)",
    )
    parser.add_argument(
        "--duration", type=float, default=None,
        help="Override audio duration in seconds (overrides preset value)",
    )
    parser.add_argument(
        "--format", type=str, default="wav",
        choices=SUPPORTED_FORMATS,
        help=f"Audio export format (default: wav). Supported: {', '.join(SUPPORTED_FORMATS)}",
    )
    parser.add_argument(
        "--hires", action="store_true",
        help="Render in high-resolution mode (48kHz/24-bit instead of default 44.1kHz/16-bit)",
    )
    parser.add_argument(
        "--seed", type=int, default=None,
        help="Global random seed for reproducible output",
    )
    parser.add_argument(
        "--solo", type=str, default=None, metavar="LAYER",
        help="Render only a single layer (by name or index, e.g. '0' or 'Gravitational Bass'). "
             "Output filename includes layer name.",
    )
    parser.add_argument(
        "--auto-template", type=str, default=None, metavar="TEMPLATE",
        choices=TEMPLATE_NAMES,
        help=(
            f"Apply a global automation template before rendering. "
            f"Options: {', '.join(TEMPLATE_NAMES)}. "
            "Does not overwrite automation already defined in the preset."
        ),
    )
    parser.add_argument(
        "--journey-template", type=str, default=None, metavar="TEMPLATE",
        choices=["drift", "flow", "pulse", "ceremony", "dawn", "shimmer"],
        help=(
            "Render a journey quick-set: multi-preset sequence with timed morphs. "
            "Options: drift (30s holds), flow (15s pingpong), pulse (8s rhythmic), "
            "ceremony (60s sacred), dawn (20s one-shot), shimmer (4s fast). "
            "Presets are auto-selected by keywords. Use with --duration for total length."
        ),
    )
    parser.add_argument(
        "--no-automation", action="store_true",
        help="Strip all automation from the preset before rendering (render a static snapshot).",
    )
    args = parser.parse_args()

    # ── Hi-res mode ──────────────────────────────────────────────────────
    if args.hires:
        from engine.config import set_hires
        set_hires()

    # ── GUI mode ──────────────────────────────────────────────────────────
    if args.gui:
        try:
            from engine.web_server import launch_gui
        except ImportError as e:
            sys.exit(
                f"Web UI requires additional packages:\n"
                f"  pip install fastapi uvicorn[standard]\n\n"
                f"Error: {e}"
            )
        launch_gui()
        return

    # ── Journey Template mode ─────────────────────────────────────────────
    if args.journey_template:
        from engine.journey import render_journey
        
        # Journey template definitions
        JOURNEY_TEMPLATES = {
            "drift": {
                "holdMin": 30, "morphMin": 12, "loop": "loop",
                "keywords": ["forest", "rain", "ocean", "river", "wind", "nature", "ambient"],
                "desc": "Very slow evolution — long holds, gradual morphs"
            },
            "flow": {
                "holdMin": 15, "morphMin": 6, "loop": "pingpong",
                "keywords": ["bowl", "bell", "gong", "singing", "crystal", "harmonic", "resonan"],
                "desc": "Smooth back-and-forth ping-pong"
            },
            "pulse": {
                "holdMin": 8, "morphMin": 2, "loop": "loop",
                "keywords": ["drone", "bass", "low", "deep", "earth", "ground", "root"],
                "desc": "Rhythmic cycling — shorter holds with crisp morphs"
            },
            "ceremony": {
                "holdMin": 60, "morphMin": 20, "loop": "loop",
                "keywords": ["sacred", "tibetan", "temple", "ritual", "ancient", "om", "mantra"],
                "desc": "Monumental pace — very long holds, slow ceremonial transitions"
            },
            "dawn": {
                "holdMin": 20, "morphMin": 8, "loop": "none",
                "keywords": ["light", "morning", "dawn", "space", "celestial", "air", "rise"],
                "desc": "One-time journey — plays through presets once"
            },
            "shimmer": {
                "holdMin": 4, "morphMin": 1, "loop": "pingpong",
                "keywords": ["shimmer", "bright", "crystal", "high", "sky", "glitter", "spark"],
                "desc": "Fast ping-pong shimmer — short holds, quick morphs"
            },
        }
        
        template = JOURNEY_TEMPLATES[args.journey_template]
        print(f"\n✨ Journey Template: {args.journey_template.upper()}")
        print(f"   {template['desc']}")
        print(f"   Hold: {template['holdMin']}s, Morph: {template['morphMin']}s, Loop: {template['loop']}\n")
        
        # Find presets matching keywords
        all_presets = discover_presets()
        if not all_presets:
            sys.exit(f"No presets found in {PRESET_DIR}/")
        
        matched_presets = []
        for keyword in template['keywords']:
            for preset_path in all_presets:
                if keyword.lower() in preset_path.stem.lower():
                    if preset_path not in matched_presets:
                        matched_presets.append(preset_path)
                        if len(matched_presets) >= 4:  # Limit to 4 presets
                            break
            if len(matched_presets) >= 4:
                break
        
        if len(matched_presets) < 2:
            sys.exit(f"Could not find enough matching presets for template '{args.journey_template}'. "
                    f"Keywords: {', '.join(template['keywords'])}")
        
        print(f"Selected {len(matched_presets)} presets:")
        for i, p in enumerate(matched_presets, 1):
            print(f"  {i}. {p.stem}")
        print()
        
        # Build journey steps
        steps = []
        for preset_path in matched_presets:
            steps.append({
                "preset_path": str(preset_path),
                "hold_s": template['holdMin'],
                "morph_s": template['morphMin']
            })
        
        # Calculate total duration if not specified
        total_duration = args.duration
        if total_duration is None:
            step_duration = template['holdMin'] + template['morphMin']
            if template['loop'] == 'none':
                total_duration = step_duration * len(steps)
            else:
                total_duration = 300.0  # Default 5 minutes for loops
            print(f"Total duration: {total_duration:.0f}s (use --duration to override)\n")
        
        # Render the journey
        print(f"Rendering journey... (total: {total_duration:.0f}s)\n")
        
        audio = render_journey(
            steps=steps,
            loop=template['loop'],
            seed=args.seed or 42,
            max_samples=None
        )
        
        # Export to file
        export_filename = f"MANTICE_Journey_{args.journey_template.capitalize()}"
        if args.seed is not None:
            export_filename += f"_seed{args.seed}"
        
        out_path = EXPORT_DIR / f"{export_filename}.{args.format}"
        export_audio(out_path, audio, fmt=args.format)
        
        sizeMB = out_path.stat().st_size / (1024 * 1024)
        print(f"\n✓ Journey rendered: {out_path.name} ({sizeMB:.1f} MB)")
        print(f"   → {out_path}")
        return

    generated_dir = PRESET_DIR / "generated"

    # ── Generate mode ─────────────────────────────────────────────────────
    if args.generate:
        print(f"Generating {args.generate_count} preset(s)"
              f"{f' (mood: {args.mood})' if args.mood else ''}...\n")
        for i in range(args.generate_count):
            preset_seed = (args.seed + i) if args.seed is not None else None
            preset = generate_preset(mood=args.mood, seed=preset_seed)
            path = save_generated_preset(preset, generated_dir)
            name = preset["meta"]["name"]
            print(f"  {i+1}. {name}")
            print(f"     → {path}")
        print(f"\n✓ {args.generate_count} preset(s) saved to {generated_dir}/")
        return

    # ── Mutate mode ───────────────────────────────────────────────────────
    if args.mutate:
        all_presets = discover_presets()
        if not all_presets:
            sys.exit(f"No presets found in {PRESET_DIR}/")

        # Find the source preset
        source_paths = find_preset_by_name(all_presets, args.mutate)
        if not source_paths:
            sys.exit(f"No preset matching '{args.mutate}'. Use --list to see available presets.")

        source_path = source_paths[0]
        print(f"Mutating: {source_path.stem} (amount: {args.amount})\n")

        # Load raw YAML for mutation (not normalised)
        import yaml as _yaml
        with source_path.open(encoding="utf-8") as f:
            raw_preset = _yaml.safe_load(f)

        for i in range(args.generate_count):
            mut_seed = (args.seed + i) if args.seed is not None else None
            mutated = mutate_preset(raw_preset, amount=args.amount, seed=mut_seed)
            path = save_generated_preset(mutated, generated_dir)
            name = mutated["meta"]["name"]
            print(f"  {i+1}. {name}")
            print(f"     → {path}")
        print(f"\n✓ {args.generate_count} mutation(s) saved to {generated_dir}/")
        return

    # ── Standard modes ────────────────────────────────────────────────────
    all_presets = discover_presets()

    # --list: print and exit
    if args.list:
        if not all_presets:
            sys.exit(f"No presets found in {PRESET_DIR}/")
        list_presets(all_presets)
        return

    # Determine which preset(s)
    if args.preset:
        if not args.preset.exists():
            sys.exit(f"Preset not found: {args.preset}")
        preset_paths = [args.preset]
    elif args.name:
        if not all_presets:
            sys.exit(f"No presets found in {PRESET_DIR}/")
        preset_paths = find_preset_by_name(all_presets, args.name)
        if not preset_paths:
            sys.exit(f"No preset matching '{args.name}'. Use --list to see available presets.")
        if not args.preview:
            print(f"Matched {len(preset_paths)} preset(s) for '{args.name}'.\n")
    else:
        preset_paths = all_presets
        if not preset_paths:
            sys.exit(f"No presets found in {PRESET_DIR}/")
        if not args.preview:
            print(f"Found {len(preset_paths)} preset(s).\n")

    # ── Preview mode ──────────────────────────────────────────────────────
    if args.preview:
        from engine.preview import PreviewSession

        if len(preset_paths) > 1:
            print(f"Preview uses the first matched preset: {preset_paths[0].stem}")

        session = PreviewSession(
            preset_path       = preset_paths[0],
            infinite          = args.infinite,
            duration_override = args.duration,
        )
        session.start()
        return

    # ── Normal render mode ────────────────────────────────────────────────
    run(preset_paths, cli_seed=args.seed, cli_duration=args.duration,
        audio_format=args.format, solo_layer=args.solo,
        auto_template=args.auto_template, no_automation=args.no_automation)


if __name__ == "__main__":
    main()
